<?php

namespace AppBundle\Repository;

/**
 * EtoilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtoilesRepository extends \Doctrine\ORM\EntityRepository
{
}
