<?php

namespace AppBundle\Repository;

/**
 * NumerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumerosRepository extends \Doctrine\ORM\EntityRepository
{
}
